export const STATUSES = [
  { id: "new", label: "New", color: "bg-blue-500", lightBg: "bg-blue-50 dark:bg-blue-950/40", text: "text-blue-700 dark:text-blue-300", border: "border-blue-200 dark:border-blue-800" },
  { id: "contacted", label: "Contacted", color: "bg-amber-500", lightBg: "bg-amber-50 dark:bg-amber-950/40", text: "text-amber-700 dark:text-amber-300", border: "border-amber-200 dark:border-amber-800" },
  { id: "interested", label: "Interested", color: "bg-violet-500", lightBg: "bg-violet-50 dark:bg-violet-950/40", text: "text-violet-700 dark:text-violet-300", border: "border-violet-200 dark:border-violet-800" },
  { id: "payment_pending", label: "Payment Pending", color: "bg-orange-500", lightBg: "bg-orange-50 dark:bg-orange-950/40", text: "text-orange-700 dark:text-orange-300", border: "border-orange-200 dark:border-orange-800" },
  { id: "converted", label: "Converted", color: "bg-emerald-500", lightBg: "bg-emerald-50 dark:bg-emerald-950/40", text: "text-emerald-700 dark:text-emerald-300", border: "border-emerald-200 dark:border-emerald-800" },
  { id: "dropped", label: "Dropped", color: "bg-red-500", lightBg: "bg-red-50 dark:bg-red-950/40", text: "text-red-700 dark:text-red-300", border: "border-red-200 dark:border-red-800" },
];

export const SOURCES = ["Ads", "Organic", "Referral"];

export const PERSONAS = [
  { id: "student", label: "Student", icon: "🎓" },
  { id: "job_seeker", label: "Job Seeker", icon: "💼" },
  { id: "freelancer", label: "Freelancer", icon: "🚀" },
  { id: "working_professional", label: "Working Professional", icon: "👔" },
  { id: "business_owner", label: "Business Owner", icon: "🏢" },
];

export const URGENCY_LEVELS = [
  { id: "low", label: "Low", color: "text-stone-500" },
  { id: "medium", label: "Medium", color: "text-amber-600" },
  { id: "high", label: "High", color: "text-orange-600" },
  { id: "urgent", label: "Urgent", color: "text-red-600" },
];

export const ENGAGEMENT_LEVELS = [
  { id: "none", label: "None" },
  { id: "low", label: "Low" },
  { id: "medium", label: "Medium" },
  { id: "high", label: "High" },
];

export const TEMPERATURES = [
  { id: "hot", label: "Hot", color: "bg-red-500", lightBg: "bg-red-50 dark:bg-red-950/40", text: "text-red-700 dark:text-red-300", border: "border-red-200 dark:border-red-800" },
  { id: "warm", label: "Warm", lightBg: "bg-amber-50 dark:bg-amber-950/40", color: "bg-amber-500", text: "text-amber-700 dark:text-amber-300", border: "border-amber-200 dark:border-amber-800" },
  { id: "cold", label: "Cold", color: "bg-sky-500", lightBg: "bg-sky-50 dark:bg-sky-950/40", text: "text-sky-700 dark:text-sky-300", border: "border-sky-200 dark:border-sky-800" },
];

export const AD_SOURCES = [
  { id: "facebook_ads", label: "Facebook Ads", group: "Ads" },
  { id: "google_ads", label: "Google Ads", group: "Ads" },
  { id: "instagram_ads", label: "Instagram Ads", group: "Ads" },
  { id: "youtube_ads", label: "YouTube Ads", group: "Ads" },
  { id: "linkedin_ads", label: "LinkedIn Ads", group: "Ads" },
  { id: "twitter_ads", label: "Twitter Ads", group: "Ads" },
  { id: "other_ads", label: "Other Ads", group: "Ads" },
  { id: "organic_search", label: "Organic Search", group: "Organic" },
  { id: "organic_social", label: "Organic Social", group: "Organic" },
  { id: "blog", label: "Blog", group: "Organic" },
  { id: "youtube_organic", label: "YouTube Organic", group: "Organic" },
  { id: "referral_student", label: "Student Referral", group: "Referral" },
  { id: "referral_affiliate", label: "Affiliate", group: "Referral" },
  { id: "referral_partner", label: "Partner", group: "Referral" },
  { id: "direct", label: "Direct", group: "Other" },
];

export const QUALIFICATION_TIMELINES = [
  { id: "immediate", label: "Immediately" },
  { id: "1_month", label: "Within 1 month" },
  { id: "3_months", label: "Within 3 months" },
  { id: "6_months", label: "Within 6 months" },
  { id: "exploring", label: "Just exploring" },
];

export const BUDGET_RANGES = [
  { id: "below_10k", label: "Below ₹10,000" },
  { id: "10k_20k", label: "₹10,000 – ₹20,000" },
  { id: "20k_30k", label: "₹20,000 – ₹30,000" },
  { id: "30k_50k", label: "₹30,000 – ₹50,000" },
  { id: "above_50k", label: "Above ₹50,000" },
];

export const COMMITMENT_LEVELS = [
  { id: "full_time", label: "Full-time" },
  { id: "part_time", label: "Part-time" },
  { id: "weekends", label: "Weekends only" },
  { id: "unsure", label: "Not sure yet" },
];

export const COURSES = [
  "Full Stack Development",
  "Digital Marketing",
  "UI/UX Design",
  "Data Science",
  "Freelancing Mastery",
];

export function generateId() {
  return Math.random().toString(36).slice(2, 10);
}

export function formatDate(iso) {
  return new Date(iso).toLocaleDateString("en-IN", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

export function formatDateTime(iso) {
  return new Date(iso).toLocaleString("en-IN", {
    day: "numeric",
    month: "short",
    hour: "2-digit",
    minute: "2-digit",
  });
}

export function isOverdue(dateStr) {
  if (!dateStr) return false;
  return new Date(dateStr) < new Date(new Date().toDateString());
}

export const MOCK_LEADS = [
  {
    id: "1",
    name: "Rahul Sharma",
    phone: "+91 98765 43210",
    email: "rahul@example.com",
    source: "Ads",
    adSource: "instagram_ads",
    status: "new",
    budget: "₹15,000",
    courseInterest: "Full Stack Development",
    tags: ["hot-lead", "student"],
    persona: "student",
    urgency: "high",
    engagement: "medium",
    leadScore: 58,
    temperature: "warm",
    notes: [{ id: "n1", text: "Inquired via Instagram ad, seems motivated", createdAt: "2026-03-20T10:30:00Z" }],
    timeline: [{ id: "t1", type: "created", description: "Lead captured from Instagram ad form", createdAt: "2026-03-20T10:00:00Z" }],
    followUpDate: "2026-03-26",
    createdAt: "2026-03-20T10:00:00Z",
  },
  {
    id: "2",
    name: "Priya Patel",
    phone: "+91 87654 32109",
    email: "priya@example.com",
    source: "Organic",
    adSource: "youtube_organic",
    status: "contacted",
    budget: "₹20,000",
    courseInterest: "Digital Marketing",
    tags: ["freelancer"],
    persona: "freelancer",
    urgency: "medium",
    engagement: "high",
    leadScore: 62,
    temperature: "warm",
    notes: [
      { id: "n1", text: "Very interested, asked about EMI options", createdAt: "2026-03-21T14:00:00Z" },
      { id: "n2", text: "Sent EMI details on WhatsApp", createdAt: "2026-03-22T11:00:00Z" },
    ],
    timeline: [
      { id: "t1", type: "created", description: "Lead created from YouTube comment", createdAt: "2026-03-19T09:00:00Z" },
      { id: "t2", type: "status_change", description: "Status changed to Contacted", createdAt: "2026-03-21T14:00:00Z" },
    ],
    followUpDate: "2026-03-25",
    createdAt: "2026-03-19T09:00:00Z",
  },
  {
    id: "3",
    name: "Amit Kumar",
    phone: "+91 76543 21098",
    email: "amit.k@example.com",
    source: "Referral",
    adSource: "referral_student",
    status: "interested",
    budget: "₹25,000",
    courseInterest: "Full Stack Development",
    tags: ["job-seeker", "referred-by-student"],
    persona: "job_seeker",
    urgency: "high",
    engagement: "high",
    leadScore: 78,
    temperature: "hot",
    qualificationData: {
      currentSituation: "Recent graduate, looking for first job",
      goal: "Get placed as a full-stack developer",
      timeline: "1_month",
      budgetRange: "20k_30k",
      previousExperience: "Built a few projects in college",
      commitment: "full_time",
      qualifiedAt: "2026-03-18T16:00:00Z",
    },
    notes: [{ id: "n1", text: "Referred by Vikram (batch 12). Strong intent.", createdAt: "2026-03-18T16:00:00Z" }],
    timeline: [
      { id: "t1", type: "created", description: "Referral from Vikram (existing student)", createdAt: "2026-03-17T10:00:00Z" },
      { id: "t2", type: "status_change", description: "Status changed to Contacted", createdAt: "2026-03-18T12:00:00Z" },
      { id: "t3", type: "status_change", description: "Status changed to Interested", createdAt: "2026-03-18T16:00:00Z" },
    ],
    followUpDate: "2026-03-27",
    createdAt: "2026-03-17T10:00:00Z",
  },
  {
    id: "4",
    name: "Sneha Reddy",
    phone: "+91 65432 10987",
    email: "sneha.r@example.com",
    source: "Ads",
    adSource: "facebook_ads",
    status: "payment_pending",
    budget: "₹18,000",
    courseInterest: "UI/UX Design",
    tags: ["student", "design-background"],
    persona: "student",
    urgency: "urgent",
    engagement: "high",
    leadScore: 82,
    temperature: "hot",
    qualificationData: {
      currentSituation: "Final year design student",
      goal: "Build a UI/UX portfolio and get freelance clients",
      timeline: "immediate",
      budgetRange: "10k_20k",
      previousExperience: "Figma basics from college",
      commitment: "full_time",
      qualifiedAt: "2026-03-20T09:00:00Z",
    },
    notes: [
      { id: "n1", text: "Ready to pay, waiting for salary credit on 1st", createdAt: "2026-03-22T09:00:00Z" },
    ],
    timeline: [
      { id: "t1", type: "created", description: "Lead from Facebook ad", createdAt: "2026-03-15T11:00:00Z" },
      { id: "t2", type: "status_change", description: "Status changed to Contacted", createdAt: "2026-03-16T10:00:00Z" },
      { id: "t3", type: "status_change", description: "Status changed to Interested", createdAt: "2026-03-18T14:00:00Z" },
      { id: "t4", type: "status_change", description: "Status changed to Payment Pending", createdAt: "2026-03-22T09:00:00Z" },
    ],
    followUpDate: "2026-04-01",
    createdAt: "2026-03-15T11:00:00Z",
  },
  {
    id: "5",
    name: "Vikram Singh",
    phone: "+91 54321 09876",
    email: "vikram.s@example.com",
    source: "Organic",
    adSource: "organic_social",
    status: "converted",
    budget: "₹22,000",
    courseInterest: "Full Stack Development",
    tags: ["job-seeker"],
    persona: "job_seeker",
    urgency: "high",
    engagement: "high",
    leadScore: 90,
    temperature: "hot",
    notes: [{ id: "n1", text: "Enrolled in Batch 14. Payment received via Razorpay.", createdAt: "2026-03-10T15:00:00Z" }],
    timeline: [
      { id: "t1", type: "created", description: "DM on Twitter", createdAt: "2026-03-01T09:00:00Z" },
      { id: "t2", type: "status_change", description: "Status changed to Contacted", createdAt: "2026-03-02T11:00:00Z" },
      { id: "t3", type: "status_change", description: "Status changed to Interested", createdAt: "2026-03-05T10:00:00Z" },
      { id: "t4", type: "status_change", description: "Status changed to Payment Pending", createdAt: "2026-03-08T14:00:00Z" },
      { id: "t5", type: "status_change", description: "Status changed to Converted", createdAt: "2026-03-10T15:00:00Z" },
    ],
    followUpDate: null,
    createdAt: "2026-03-01T09:00:00Z",
  },
  {
    id: "6",
    name: "Ananya Gupta",
    phone: "+91 43210 98765",
    email: "ananya@example.com",
    source: "Ads",
    adSource: "google_ads",
    status: "new",
    budget: "₹10,000",
    courseInterest: "Freelancing Mastery",
    tags: ["student", "budget-conscious"],
    persona: "student",
    urgency: "low",
    engagement: "none",
    leadScore: 12,
    temperature: "cold",
    notes: [],
    timeline: [{ id: "t1", type: "created", description: "Lead from Google ad", createdAt: "2026-03-24T08:00:00Z" }],
    followUpDate: "2026-03-26",
    createdAt: "2026-03-24T08:00:00Z",
  },
  {
    id: "7",
    name: "Karan Mehta",
    phone: "+91 32109 87654",
    email: "karan.m@example.com",
    source: "Referral",
    adSource: "referral_partner",
    status: "contacted",
    budget: "₹30,000",
    courseInterest: "Data Science",
    tags: ["working-professional"],
    persona: "working_professional",
    urgency: "medium",
    engagement: "medium",
    leadScore: 52,
    temperature: "warm",
    notes: [{ id: "n1", text: "Works at TCS, wants to switch to data role", createdAt: "2026-03-23T17:00:00Z" }],
    timeline: [
      { id: "t1", type: "created", description: "Referral from LinkedIn post", createdAt: "2026-03-22T10:00:00Z" },
      { id: "t2", type: "status_change", description: "Status changed to Contacted", createdAt: "2026-03-23T17:00:00Z" },
    ],
    followUpDate: "2026-03-28",
    createdAt: "2026-03-22T10:00:00Z",
  },
  {
    id: "8",
    name: "Deepika Joshi",
    phone: "+91 21098 76543",
    email: "deepika.j@example.com",
    source: "Organic",
    adSource: "organic_search",
    status: "dropped",
    budget: "₹12,000",
    courseInterest: "Digital Marketing",
    tags: ["student"],
    persona: "student",
    urgency: "low",
    engagement: "low",
    leadScore: 18,
    temperature: "cold",
    notes: [{ id: "n1", text: "Budget too low, couldn't afford. Might revisit later.", createdAt: "2026-03-20T13:00:00Z" }],
    timeline: [
      { id: "t1", type: "created", description: "Inquiry via website form", createdAt: "2026-03-14T10:00:00Z" },
      { id: "t2", type: "status_change", description: "Status changed to Contacted", createdAt: "2026-03-15T11:00:00Z" },
      { id: "t3", type: "status_change", description: "Status changed to Dropped", createdAt: "2026-03-20T13:00:00Z" },
    ],
    followUpDate: null,
    createdAt: "2026-03-14T10:00:00Z",
  },
  {
    id: "9",
    name: "Rohan Nair",
    phone: "+91 10987 65432",
    email: "rohan.n@example.com",
    source: "Ads",
    adSource: "instagram_ads",
    status: "new",
    budget: "₹17,000",
    courseInterest: "UI/UX Design",
    tags: ["student"],
    persona: "student",
    urgency: "medium",
    engagement: "low",
    leadScore: 28,
    temperature: "cold",
    notes: [],
    timeline: [{ id: "t1", type: "created", description: "Lead from Instagram story ad", createdAt: "2026-03-25T07:00:00Z" }],
    followUpDate: "2026-03-27",
    createdAt: "2026-03-25T07:00:00Z",
  },
  {
    id: "10",
    name: "Meera Iyer",
    phone: "+91 09876 54321",
    email: "meera.i@example.com",
    source: "Organic",
    adSource: "blog",
    status: "interested",
    budget: "₹28,000",
    courseInterest: "Data Science",
    tags: ["working-professional", "hot-lead"],
    persona: "working_professional",
    urgency: "high",
    engagement: "high",
    leadScore: 76,
    temperature: "hot",
    qualificationData: {
      currentSituation: "Working as data analyst at a startup",
      goal: "Transition to data science role with higher pay",
      timeline: "1_month",
      budgetRange: "20k_30k",
      previousExperience: "Python, SQL, basic ML",
      commitment: "part_time",
      qualifiedAt: "2026-03-23T10:00:00Z",
    },
    notes: [
      { id: "n1", text: "Strong intent, comparing with other courses", createdAt: "2026-03-23T10:00:00Z" },
      { id: "n2", text: "Sent comparison doc and success stories", createdAt: "2026-03-24T09:00:00Z" },
    ],
    timeline: [
      { id: "t1", type: "created", description: "Found via blog post", createdAt: "2026-03-20T08:00:00Z" },
      { id: "t2", type: "status_change", description: "Status changed to Contacted", createdAt: "2026-03-21T11:00:00Z" },
      { id: "t3", type: "status_change", description: "Status changed to Interested", createdAt: "2026-03-23T10:00:00Z" },
    ],
    followUpDate: "2026-03-26",
    createdAt: "2026-03-20T08:00:00Z",
  },
];
